config/routes.rb
Rails.application.routes.draw do
  # API
  namespace :api do
    namespace :v1 do
      resources :wines, except: [:new, :edit]
      resources :regions, except: [:new, :edit]
      resources :appellations, except: [:new, :edit]
      resources :vineyards, except: [:new, :edit]
      resources :varietals, except: [:new, :edit]
      resources :wine_types, except: [:new, :edit]
    end
  end

  resources :wines
  resources :regions, except: [:update, :edit]
  resources :appellations, except: [:update, :edit]
  resources :vineyards, except: [:update, :edit]
  resources :varietals, except: [:update, :edit]
  resources :wine_types, except: [:update, :edit]
end

app/models/varietal.rb
class Varietal < ActiveRecord::Base
  validates :name, presence: true
  validates :wine_type, presence: true

  belongs_to :wine_type
  has_many :wines
end

app/controllers/api/v1/varietals_controller.rb
class Api::V1::VarietalsController < Api::ApiController
  before_action :set_varietal, except: [:index, :create]

  def index
    render status: 200, json: Varietal.all
  end

  def show
    if @varietal
      render status: 200, json: @varietal
    else
      render status: 404, json: {status: "Not Found",
                                 message: "Varietal not found in database" }
    end
  end

  def create
    varietal = Varietal.find_or_initialize_by(varietal_params)

    if varietal.save
      render status: 200, json: varietal
    else
      render status: 422, json: {
        status: "Unable to create varietal",
        errors: varietal.errors.full_messages
      }
    end
  end

  def update
    if @varietal.update(varietal_params)
      render status: 200, json: @varietal
    else
      render status: 422, json: {
        status: "Unable to update varietal",
        errors: varietal.errors.full_messages
      }
    end
  end

  def destroy
    if @varietal
      @varietal.destroy
      render status: 200, json: {message: "Varietal successfully deleted"}
    else
      render status: 404, json: {status: "Not Found",
                                 message: "Varietal not found in database" }
    end
  end

  private

  def set_varietal
    @varietal = Varietal.find_by(id: params[:id])
  end

  def varietal_params
    cleaned_input = params.require(:varietal).permit(:name, :wine_type_id)
    titlecase_name_attr(cleaned_input)
  end

  def titlecase_name_attr(hash)
    hash.merge(name: hash[:name].titlecase)
  end
end

app/controllers/varietals_controller.rb
class VarietalsController < ApplicationController
  def index
    @varietals = Varietal.all
  end

  def new
    @varietal = Varietal.new
  end

  def create
    normalized_params = normalize(varietal_params)

    @varietal = Varietal.find_or_create_by(normalized_params)

    if @varietal.save
      flash[:success] = "Varietal successfully added to or found in database"
      redirect_to varietals_path
    else
      flash[:danger] = "varietal not saved"
      render :new
    end
  end

  private

  def varietal_params
    params.require(:varietal).permit(:name,:wine_type_id)
  end

  def normalize(hash)
    hash.each_with_object({}) do |(key, value), memo|
      memo[key] = value.titlecase
    end
  end
end

app/views/varietals/_form.html.erb
<%= form_for @varietal do |f| %>
  <% if @varietal.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@varietal.errors.count, "error") %> prohibited this varietal from being saved:</h2>

        <ul>
        <% @varietal.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Select Wine Type" %>
    <%= f.select :wine_type_id, WineType.all.collect {|w| [w.name, w.id]}, {include_blank: false}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/varietals/_varietal.html.erb
<tr>
  <td><%= varietal.name %></td>
  <td><%= varietal.wines.count %></td>
</tr>

app/views/varietals/index.html.erb
<h1 class="text-center">Varietal List</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Wine Count</th>
    </tr>
  </thead>
  <tbody>

    <% @varietals.each do |varietal| %>
      <%= render varietal %>
    <% end %>

  </tbody>
</table>

<%= link_to "Create Varietal", new_varietal_path %>

app/views/varietals/new.html.erb
<h1>Create a New Varietal</h1>

<%= render 'form' %>

<%= link_to "Back", varietals_path %>