config/routes.rb
Rails.application.routes.draw do
  # API
  namespace :api do
    namespace :v1 do
      resources :wines, except: [:new, :edit]
      resources :regions, except: [:new, :edit]
      resources :appellations, except: [:new, :edit]
      resources :vineyards, except: [:new, :edit]
      resources :varietals, except: [:new, :edit]
      resources :wine_types, except: [:new, :edit]
    end
  end

  resources :wines
  resources :regions, except: [:update, :edit]
  resources :appellations, except: [:update, :edit]
  resources :vineyards, except: [:update, :edit]
  resources :varietals, except: [:update, :edit]
  resources :wine_types, except: [:update, :edit]
end

app/models/region.rb
class Region < ActiveRecord::Base
  validates :name, presence: true

  has_many :appellations
  has_many :wines, through: :appellations
end

app/controllers/api/v1/regions_controller.rb
class Api::V1::RegionsController < Api::ApiController
  before_action :set_region, except: [:index, :create]

  def index
    render status: 200, json: Region.all
  end

  def show
    if @region
      render status: 200, json: @region
    else
      render status: 404, json: {status: "Not Found",
                                 message: "Region not found in database" }
    end
  end

  def create
    region = Region.find_or_initialize_by(region_params)

    if region.save
      render status: 200, json: region
    else
      render status: 422, json: {
        status: "Unable to create region",
        errors: region.errors.full_messages
      }
    end
  end

  def update
    if @region.update(region_params)
      render status: 200, json: @region
    else
      render status: 422, json: {
        status: "Unable to update region",
        errors: region.errors.full_messages
      }
    end
  end

  def destroy
    if @region
      @region.destroy
      render status: 200, json: {message: "Region successfully deleted"}
    else
      render status: 404, json: {status: "Not Found",
                                 message: "Region not found in database" }
    end
  end

  private

  def set_region
    @region = Region.find_by(id: params[:id])
  end

  def region_params
    cleaned_input = params.require(:region).permit(:name)
    titlecase_name_attr(cleaned_input)
  end

  def titlecase_name_attr(hash)
    hash.merge(name: hash[:name].titlecase)
  end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  def index
    @regions = Region.all
  end

  def new
    @region = Region.new
  end

  def create
    normalized_params = normalize(region_params)

    @region = Region.find_or_create_by(normalized_params)

    if @region.save
      flash[:success] = "Region successfully added to or found in database"
      redirect_to regions_path
    else
      flash[:danger] = "Region not saved"
      render :new
    end
  end

  private

  def region_params
    params.require(:region).permit(:name)
  end

  def normalize(hash)
    hash.each_with_object({}) do |(key, value), memo|
      memo[key] = value.titlecase
    end
  end
end

app/views/regions/_form.html.erb
<%= form_for @region do |f| %>
  <% if @region.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@region.errors.count, "error") %> prohibited this region from being saved:</h2>

        <ul>
        <% @region.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/regions/_region.html.erb
<tr>
  <td><%= region.name %></td>
  <td><%= region.wines.count %></td>
</tr>

app/views/regions/index.html.erb
<h1 class="text-center">Region List</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Wine Count</th>
    </tr>
  </thead>
  <tbody>

    <% @regions.each do |region| %>
      <%= render region %>
    <% end %>

  </tbody>
</table>

<%= link_to "Create Region", new_region_path %>

app/views/regions/new.html.erb
<h1>Create a New Region</h1>

<%= render 'form' %>

<%= link_to "Back", regions_path %>