config/routes.rb
Rails.application.routes.draw do
  # API
  namespace :api do
    namespace :v1 do
      resources :wines, except: [:new, :edit]
      resources :regions, except: [:new, :edit]
      resources :appellations, except: [:new, :edit]
      resources :vineyards, except: [:new, :edit]
      resources :varietals, except: [:new, :edit]
      resources :wine_types, except: [:new, :edit]
    end
  end

  resources :wines
  resources :regions, except: [:update, :edit]
  resources :appellations, except: [:update, :edit]
  resources :vineyards, except: [:update, :edit]
  resources :varietals, except: [:update, :edit]
  resources :wine_types, except: [:update, :edit]
end

app/models/wine.rb
class Wine < ActiveRecord::Base
  validates :name, presence: true
  validates :price_min, presence: true
  validates :price_max, presence: true
  validates :price_retail, presence: true

  has_many :winetraits, class_name: "WineTrait", dependent: :destroy
  has_many :traits, through: :winetraits
  belongs_to :appellation
  belongs_to :varietal
  belongs_to :vineyard
end

app/models/wine_type.rb
class WineType < ActiveRecord::Base
  validates :name, presence: true

  has_many :varietals
end

app/controllers/api/v1/wines_controller.rb
class Api::V1::WinesController < Api::ApiController
  before_action :set_wine, except: [:index, :create]

  def index
    render status: 200, json: Wine.all
  end

  def show
    if @wine
      render status: 200, json: @wine
    else
      render status: 404, json: {status: "Not Found",
                                 message: "Wine not found in database" }
    end
  end

  def create
    wine = Wine.find_or_initialize_by(wine_params)

    if wine.save
      render status: 200, json: wine
    else
      render status: 422, json: {
        status: "Unable to create wine",
        errors: wine.errors.full_messages
      }
    end
  end

  def update
    if @wine.update(wine_params)
      render status: 200, json: @wine
    else
      render status: 422, json: {
        status: "Unable to update wine",
        errors: wine.errors.full_messages
      }
    end
  end

  def destroy
    if @wine
      @wine.destroy
      render status: 200, json: {message: "Wine successfully deleted"}
    else
      render status: 404, json: {status: "Not Found",
                                 message: "Wine not found in database" }
    end
  end

  private

  def set_wine
    @wine = Wine.find_by(id: params[:id])
  end

  def wine_params
    cleaned_input = params.require(:wine).permit(:name, :price_min, :price_max,
                                                 :price_retail, :year,
                                                 :varietal_id,
                                                 :vineyard_id,:appellation_id)

    titlecase_name_attr(cleaned_input)
  end

  def titlecase_name_attr(hash)
    hash.merge(name: hash[:name].titlecase)
  end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: [:show, :edit, :update]

  def index
    @wines = Wine.all
  end

  def show
  end

  def edit
  end

  def new
    @wine = Wine.new
  end

  def create
    @wine = Wine.find_or_initialize_by(wine_params)

    if @wine.save
      flash[:success] = "Wine successfully created."
      redirect_to @wine
    else
      flash[:danger] = "Wine not created."
      render :new
    end
  end

  def update
    if @wine.update_attributes(wine_params)
      flash[:success] = "Wine successfully updated."
      redirect_to @wine
    else
      flash[:danger] = "Wine was not updated."
      render :edit
    end
  end

  private

  def set_wine
    @wine = Wine.find_by(id: params[:id])
  end

  def wine_params
    clean_inputs = params.require(:wine).permit(:name, :price_max,
                                                :price_retail,
                                                :price_min,:varietal_id,
                                                :vineyard_id, :appellation_id)

    titlecase_name(clean_inputs)
  end

  def titlecase_name(hash)
    hash.merge(name: hash[:name].titlecase)
  end
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/wines/_form.html.erb
<%= form_for @wine  do |f| %>
  <% if @wine.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

        <ul>
        <% @wine.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Max Price" %>
    <%= f.text_field :price_max, class: "form-control", type: "number", step: "0.01"%>
  </div>

  <div class="form-group">
    <%= f.label "Retail Price" %>
    <%= f.text_field :price_retail, class: "form-control", type: "number", step: "0.01"%>
  </div>

  <div class="form-group">
    <%= f.label "Min Price" %>
    <%= f.text_field :price_min, class: "form-control", type: "number", step: "0.01"%>
  </div>


  <div class="form-group">
    <%= f.label "Select Varietal" %>
    <%= f.select :varietal_id, Varietal.all.collect {|v| [v.name, v.id]}, {include_blank: true}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Select Appellation" %>
    <%= f.select :appellation_id, Appellation.all.collect {|a| [a.name, a.id]}, {include_blank: true}, class: "form-control" %>
  </div>

  <%= link_to "Create New Appellation", new_appellation_path %>

  <div class="form-group">
    <%= f.label "Select Vineyard" %>
    <%= f.select :vineyard_id, Vineyard.all.collect {|v| [v.name, v.id]}, {include_blank: true}, class: "form-control" %>
  </div>

  <%= link_to "Create New Vineyard", new_vineyard_path %>

  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/wines/_wine.html.erb
<tr>
  <td><%= wine.name %></td>
  <td><%= wine.appellation.name %></td>
  <td><%= wine.varietal.name %></td>
  <td><%= wine.vineyard.name %></td>
</tr>

app/views/wines/edit.html.erb
<h1>Edit Current Wine</h1>

<%= render 'form' %>

<%= link_to "Back", wines_path %>

app/views/wines/index.html.erb
<h1 class="text-center">Wine List</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Appellation</th>
      <th>Varietal</th>
      <th>Vineyard</th>
    </tr>
  </thead>
  <tbody>

    <% @wines.each do |wine| %>
      <%= render wine %>
    <% end %>

  </tbody>
</table>

app/views/wines/new.html.erb
<h1>Add a Wine to Our Wine List</h1>

<%= render 'form' %>

<%= link_to "Back", wines_path %>

app/views/wines/show.html.erb
<h1>Viewing Page for <%= @wine.name %></h1>

<p><strong>Appellation:</strong> <%= @wine.appellation.name %></p>
<p><strong>Varietal:</strong> <%= @wine.varietal.name %></p>
<p><strong>Vineyard:</strong> <%= @wine.vineyard.name %></p>