config/routes.rb
Rails.application.routes.draw do
  # API
  namespace :api do
    namespace :v1 do
      resources :wines, except: [:new, :edit]
      resources :regions, except: [:new, :edit]
      resources :appellations, except: [:new, :edit]
      resources :vineyards, except: [:new, :edit]
      resources :varietals, except: [:new, :edit]
      resources :wine_types, except: [:new, :edit]
    end
  end

  resources :wines
  resources :regions, except: [:update, :edit]
  resources :appellations, except: [:update, :edit]
  resources :vineyards, except: [:update, :edit]
  resources :varietals, except: [:update, :edit]
  resources :wine_types, except: [:update, :edit]
end

app/controllers/api/v1/wine_types_controller.rb
class Api::V1::WineTypesController < Api::ApiController
  before_action :set_wine_type, except: [:index, :create]

  def index
    render status: 200, json: WineType.all
  end

  def show
    if @wine_type
      render status: 200, json: @wine_type
    else
      render status: 404, json: {status: "Not Found",
                                 message: "WineType not found in database" }
    end
  end

  def create
    wine_type = WineType.find_or_initialize_by(wine_type_params)

    if wine_type.save
      render status: 200, json: wine_type
    else
      render status: 422, json: {
        status: "Unable to create wine type",
        errors: wine_type.errors.full_messages
      }
    end
  end

  def update
    if @wine_type.update(wine_type_params)
      render status: 200, json: @wine_type
    else
      render status: 422, json: {
        status: "Unable to update wine type",
        errors: wine_type.errors.full_messages
      }
    end
  end

  def destroy
    if @wine_type
      @wine_type.destroy
      render status: 200, json: {message: "Wine type successfully deleted"}
    else
      render status: 404, json: {status: "Not Found",
                                 message: "Wine type not found in database" }
    end
  end

  private

  def set_wine_type
    @wine_type = WineType.find_by(id: params[:id])
  end

  def wine_type_params
    cleaned_input = params.require(:wine_type).permit(:name)
    titlecase_name_attr(cleaned_input)
  end

  def titlecase_name_attr(hash)
    hash.merge(name: hash[:name].titlecase)
  end
end

app/controllers/wine_types_controller.rb
class WineTypesController < ApplicationController
  def index
    @wine_types = WineType.all
  end

  def new
    @wine_type = WineType.new
  end

  def create
    normalized_params = normalize(region_params)

    @wine_type = WineType.find_or_create_by(normalized_params)

    if @wine_type.save
      flash[:success] = "Wine Type successfully added to or found in database"
      redirect_to wine_types_path
    else
      flash[:danger] = "Wine Type not saved"
      render :new
    end
  end

  private

  def region_params
    params.require(:wine_type).permit(:name)
  end

  def normalize(hash)
    hash.each_with_object({}) do |(key, value), memo|
      memo[key] = value.titlecase
    end
  end
end

app/views/wine_types/_form.html.erb
<%= form_for @wine_type  do |f| %>
  <% if @wine_type.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@wine_type.errors.count, "error") %> prohibited this wine type from being saved:</h2>

        <ul>
        <% @wine_type.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/wine_types/_wine_type.html.erb
<tr>
  <td><%= wine_type.name %></td>
  <td><%= wine_type.varietals.count %></td>
</tr>

app/views/wine_types/index.html.erb
<h1>Viewing Wine Types</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Varietal Count</th>
    </tr>
  </thead>
  <tbody>

    <% @wine_types.each do |wine_type| %>
      <%= render wine_type %>
    <% end %>

  </tbody>
</table>

<%= link_to "Create Wine Type", new_wine_type_path %>

app/views/wine_types/new.html.erb
<h1>Create a New Wine Type</h1>

<%= render 'form' %>

<%= link_to "Back", wine_types_path %>